// Vue.js オブジェクト作成
var vm=new Vue({
    el:'#app',
    data:{
        items:[
            {
                name:'Vue',
                url:'./Vue/'
            },
            {
                name:'Table',
                url:'./Table/'
            },
            {
                name:'ScrollTable',
                url:'./ScrollTable/'
            },
            {
                name:'CheckTable',
                url:'./CheckTable/'
            },
            {
                name:'RadioTable',
                url:'./RadioTable/'
            },
            {
                name:'Bootstrap-Tabs',
                url:'./Bootstrap-Tabs/'
            },
            {
                name:'Vue-Tabs',
                url:'./Vue-Tabs/'
            }
        ]
    }
});
