// データ定義
var data1= {
    trim:{
        start:"00:05:00.000",
        end:"00:30:00.000",
        duration:"00:25:00.000"
    },
    size:{
        x:480,
        y:360
    },
    option:{
        fadein:"00:00:05.000",
        fadeout:"00:00:10.000"
    }
}
var data2= {
    trim:{
        start:"00:10:00.000",
        end:"00:25:00.000",
        duration:"00:15:00.000"
    },
    size:{
        x:800,
        y:600
    },
    option:{
        fadein:"00:00:10.000",
        fadeout:"00:00:05.000"
    }
}
var func=function(){
    return data;
}
var func2=function(){
    if (vm.id==data1.size.x){
        data=data2;
        vm.id=data2.size.x;
    }else{
        data=data1;
        vm.id=data1.size.x;
    }
}

// Vue.js オブジェクト作成
var vm=new Vue({
    el:'#app',
    data:{
        id:'',
        start:'00:00:00.000',
        end:'00:00:00.000',
        duration:'00:00:00.000',
        x:0,
        y:0,
        fadein:'00:00:00.000',
        fadeout:'00:00:00.000'
    },
    watch:{
        id:function(e){
            tmp=func()
            this.start=tmp.trim.start
            this.end=tmp.trim.end
            this.duration=tmp.trim.duration
            this.x=tmp.size.x
            this.y=tmp.size.y
            this.fadein=tmp.option.fadein
            this.fadeout=tmp.option.fadeout
        }
    }
});
